version: '3'
services:
  # Your Java Application
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Tells App to look for a server named 'db'
      DB_HOST: db
      DB_PASSWORD: root

  # The MySQL Database
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    # This loads the data. Ensure world.sql is in your 'docker' folder or root.
    volumes:
      - ./docker/world.sql:/docker-entrypoint-initdb.d/world.sql